[program:nextjs]
command=npx next start -p 3000 -H 127.0.0.1
directory=/app/frontend
environment=PORT="3000",HOSTNAME="127.0.0.1"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
